# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import device_control_pb2 as device__control__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in device_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDevices = channel.unary_unary(
                '/mirrorsync.DeviceControl/ListDevices',
                request_serializer=device__control__pb2.Empty.SerializeToString,
                response_deserializer=device__control__pb2.DeviceList.FromString,
                _registered_method=True)
        self.SendCommand = channel.unary_unary(
                '/mirrorsync.DeviceControl/SendCommand',
                request_serializer=device__control__pb2.CommandRequest.SerializeToString,
                response_deserializer=device__control__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.GetDeviceStatus = channel.unary_unary(
                '/mirrorsync.DeviceControl/GetDeviceStatus',
                request_serializer=device__control__pb2.DeviceStatusRequest.SerializeToString,
                response_deserializer=device__control__pb2.DeviceStatusResponse.FromString,
                _registered_method=True)
        self.StartMirror = channel.unary_unary(
                '/mirrorsync.DeviceControl/StartMirror',
                request_serializer=device__control__pb2.MirrorRequest.SerializeToString,
                response_deserializer=device__control__pb2.MirrorResponse.FromString,
                _registered_method=True)
        self.StopMirror = channel.unary_unary(
                '/mirrorsync.DeviceControl/StopMirror',
                request_serializer=device__control__pb2.MirrorRequest.SerializeToString,
                response_deserializer=device__control__pb2.MirrorResponse.FromString,
                _registered_method=True)


class DeviceControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartMirror(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopMirror(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=device__control__pb2.Empty.FromString,
                    response_serializer=device__control__pb2.DeviceList.SerializeToString,
            ),
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=device__control__pb2.CommandRequest.FromString,
                    response_serializer=device__control__pb2.CommandResponse.SerializeToString,
            ),
            'GetDeviceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceStatus,
                    request_deserializer=device__control__pb2.DeviceStatusRequest.FromString,
                    response_serializer=device__control__pb2.DeviceStatusResponse.SerializeToString,
            ),
            'StartMirror': grpc.unary_unary_rpc_method_handler(
                    servicer.StartMirror,
                    request_deserializer=device__control__pb2.MirrorRequest.FromString,
                    response_serializer=device__control__pb2.MirrorResponse.SerializeToString,
            ),
            'StopMirror': grpc.unary_unary_rpc_method_handler(
                    servicer.StopMirror,
                    request_deserializer=device__control__pb2.MirrorRequest.FromString,
                    response_serializer=device__control__pb2.MirrorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mirrorsync.DeviceControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mirrorsync.DeviceControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorsync.DeviceControl/ListDevices',
            device__control__pb2.Empty.SerializeToString,
            device__control__pb2.DeviceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorsync.DeviceControl/SendCommand',
            device__control__pb2.CommandRequest.SerializeToString,
            device__control__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorsync.DeviceControl/GetDeviceStatus',
            device__control__pb2.DeviceStatusRequest.SerializeToString,
            device__control__pb2.DeviceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartMirror(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorsync.DeviceControl/StartMirror',
            device__control__pb2.MirrorRequest.SerializeToString,
            device__control__pb2.MirrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopMirror(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirrorsync.DeviceControl/StopMirror',
            device__control__pb2.MirrorRequest.SerializeToString,
            device__control__pb2.MirrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
