# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device_control.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'device_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x65vice_control.proto\x12\nmirrorsync\"\x07\n\x05\x45mpty\"^\n\x06\x44\x65vice\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x17\n\x0f\x61gent_connected\x18\x04 \x01(\x08\x12\x0c\n\x04port\x18\x05 \x01(\x05\"1\n\nDeviceList\x12#\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x12.mirrorsync.Device\"\x9f\x01\n\x0e\x43ommandRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\r\n\x05\x65nd_x\x18\x04 \x01(\x02\x12\r\n\x05\x65nd_y\x18\x05 \x01(\x02\x12\x13\n\x0b\x64uration_ms\x18\x06 \x01(\x05\x12\x0c\n\x04text\x18\x07 \x01(\t\x12\x10\n\x08key_code\x18\x08 \x01(\x05\x12\x16\n\x0etarget_devices\x18\t \x03(\t\"J\n\x0f\x43ommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rdevices_count\x18\x03 \x01(\x05\"%\n\x13\x44\x65viceStatusRequest\x12\x0e\n\x06serial\x18\x01 \x01(\t\"e\n\x14\x44\x65viceStatusResponse\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x17\n\x0f\x61gent_connected\x18\x03 \x01(\x08\x12\x14\n\x0clast_ping_ms\x18\x04 \x01(\x03\"\x1f\n\rMirrorRequest\x12\x0e\n\x06serial\x18\x01 \x01(\t\"2\n\x0eMirrorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf2\x02\n\rDeviceControl\x12\x38\n\x0bListDevices\x12\x11.mirrorsync.Empty\x1a\x16.mirrorsync.DeviceList\x12\x46\n\x0bSendCommand\x12\x1a.mirrorsync.CommandRequest\x1a\x1b.mirrorsync.CommandResponse\x12T\n\x0fGetDeviceStatus\x12\x1f.mirrorsync.DeviceStatusRequest\x1a .mirrorsync.DeviceStatusResponse\x12\x44\n\x0bStartMirror\x12\x19.mirrorsync.MirrorRequest\x1a\x1a.mirrorsync.MirrorResponse\x12\x43\n\nStopMirror\x12\x19.mirrorsync.MirrorRequest\x1a\x1a.mirrorsync.MirrorResponseB\x14\xaa\x02\x11MirrorSync.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021MirrorSync.Protos'
  _globals['_EMPTY']._serialized_start=36
  _globals['_EMPTY']._serialized_end=43
  _globals['_DEVICE']._serialized_start=45
  _globals['_DEVICE']._serialized_end=139
  _globals['_DEVICELIST']._serialized_start=141
  _globals['_DEVICELIST']._serialized_end=190
  _globals['_COMMANDREQUEST']._serialized_start=193
  _globals['_COMMANDREQUEST']._serialized_end=352
  _globals['_COMMANDRESPONSE']._serialized_start=354
  _globals['_COMMANDRESPONSE']._serialized_end=428
  _globals['_DEVICESTATUSREQUEST']._serialized_start=430
  _globals['_DEVICESTATUSREQUEST']._serialized_end=467
  _globals['_DEVICESTATUSRESPONSE']._serialized_start=469
  _globals['_DEVICESTATUSRESPONSE']._serialized_end=570
  _globals['_MIRRORREQUEST']._serialized_start=572
  _globals['_MIRRORREQUEST']._serialized_end=603
  _globals['_MIRRORRESPONSE']._serialized_start=605
  _globals['_MIRRORRESPONSE']._serialized_end=655
  _globals['_DEVICECONTROL']._serialized_start=658
  _globals['_DEVICECONTROL']._serialized_end=1028
# @@protoc_insertion_point(module_scope)
